In [1]:
import numpy as np

### Making an array

In [2]:
list =[6,7,8]
np.array(list)

array([6, 7, 8])

In [3]:
arr=np.array([6,7,8])
arr

array([6, 7, 8])

In [4]:
list_of_list=([1,2,3],[4,5,6],[7,8,9])
np.array(list_of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Arange

In [5]:
np.arange(5,28)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27])

In [6]:
np.arange(5,36,6)

array([ 5, 11, 17, 23, 29, 35])

### An array of zeros

In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

### An array of ones

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

### Linspace

In [11]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [12]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

### Random

In [13]:
np.random.random(20)

array([0.4906261 , 0.48156311, 0.52162247, 0.48868744, 0.43877839,
       0.30769904, 0.0114696 , 0.53274969, 0.64266907, 0.03571601,
       0.12451939, 0.38914245, 0.02506751, 0.88459667, 0.68151096,
       0.7593201 , 0.8984874 , 0.76195376, 0.20092941, 0.66850771])

In [14]:
np.random.rand(2,2)

array([[0.58707821, 0.39611939],
       [0.7817112 , 0.68398186]])

In [15]:
np.random.randn(2,2)

array([[-0.94203188, -1.30464483],
       [-0.14136011,  0.46786511]])

In [16]:
np.random.randint(0,10,15)

array([0, 4, 5, 4, 6, 4, 3, 8, 0, 5, 7, 3, 3, 9, 3])

In [17]:
np.random.randint(20,56,100)

array([53, 47, 47, 34, 34, 43, 52, 41, 30, 49, 32, 45, 35, 41, 47, 55, 47,
       50, 20, 33, 44, 24, 38, 22, 50, 55, 26, 23, 39, 48, 51, 37, 52, 33,
       38, 44, 34, 34, 23, 55, 26, 54, 48, 39, 29, 54, 46, 42, 30, 53, 36,
       40, 36, 52, 20, 28, 29, 25, 25, 45, 26, 29, 54, 26, 29, 51, 41, 25,
       48, 55, 20, 38, 24, 42, 55, 43, 40, 25, 53, 51, 20, 48, 22, 28, 33,
       41, 20, 34, 21, 44, 23, 49, 54, 27, 42, 37, 23, 30, 24, 39])

In [18]:
array = np.arange(2,20)
array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [19]:
array1= np.random.randint(0,10,5)
array1

array([7, 6, 2, 7, 0])

In [20]:
array.max()

19

In [21]:
array.min()

2

In [22]:
array.argmax()

17

In [23]:
array.argmin()

0

In [24]:
array1.max()

7

In [25]:
array1.min()

0

In [26]:
array1.argmax()

0

In [27]:
array1.argmin()

4

In [28]:
array.dtype

dtype('int32')

In [29]:
array1.dtype

dtype('int32')

In [30]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
a = np.random.rand(2,5)
a

array([[0.67200579, 0.0309479 , 0.16162016, 0.85724022, 0.5047155 ],
       [0.8263429 , 0.2262722 , 0.07598234, 0.5868539 , 0.71019299]])

In [32]:
a.T

array([[0.67200579, 0.8263429 ],
       [0.0309479 , 0.2262722 ],
       [0.16162016, 0.07598234],
       [0.85724022, 0.5868539 ],
       [0.5047155 , 0.71019299]])

In [33]:
array = np.arange(10,28)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [34]:
array= array.reshape(3,6)
array

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27]])

In [35]:
array[1]=100
array

array([[ 10,  11,  12,  13,  14,  15],
       [100, 100, 100, 100, 100, 100],
       [ 22,  23,  24,  25,  26,  27]])

In [36]:
array = np.arange(10,100)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [37]:
array[1:12]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [38]:
subset_array = array[0:7]
subset_array

array([10, 11, 12, 13, 14, 15, 16])

In [39]:
array[:]=1001
array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001])

### TWO DIMENSIONAL ARRAY

In [40]:
matrix=np.array(([24,12,2,15],[15,2,54,65],[15,2,54,65],[56,76,24,7]))
matrix

array([[24, 12,  2, 15],
       [15,  2, 54, 65],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [41]:
matrix[2][2]

54

In [42]:
matrix[1][2]

54

In [43]:
matrix[:,2]

array([ 2, 54, 54, 24])

In [44]:
matrix[2]

array([15,  2, 54, 65])

In [45]:
array = np.arange(1,31)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [46]:
array+array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [47]:
np.exp(array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [48]:
np.sqrt(array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [49]:
np.log(array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [50]:
np.max(array)

30

In [51]:
np.min(array)

1

In [52]:
np.argmax(array)

29

In [53]:
np.argmin(array)

0

In [54]:
np.square(array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [55]:
np.std(array)

8.65544144839919

In [56]:
np.var(array)

74.91666666666667

In [57]:
np.mean(array)

15.5

In [58]:
array = np.random.randn(3,4)
array

array([[ 0.45492413, -0.13906977, -1.59573709, -0.48729786],
       [ 0.25714562,  1.05616128,  0.06886103,  0.92175755],
       [-0.07154461, -0.62021833,  0.22018466,  0.13084488]])

In [59]:
np.round(array,decimals = 3)

array([[ 0.455, -0.139, -1.596, -0.487],
       [ 0.257,  1.056,  0.069,  0.922],
       [-0.072, -0.62 ,  0.22 ,  0.131]])

In [60]:
sports=np.array(["golf","cricket","football","cricket","basketball"])
np.unique(sports)

array(['basketball', 'cricket', 'football', 'golf'], dtype='<U10')


#### 1) Create a null vector of size 10
#### 2)Create a null vector of size 10 but the 5th value should be 1
#### 3)Create a vector with vaues ranging from 10 to 65
#### 4) Reverse the above vector
#### 5)Create a 3x3 matrix with values ranging from 0 to 8

In [61]:
#1
vector = np.zeros(10)
vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [62]:
#2
vector = np.zeros(10)
vector[4]=1
vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [63]:
#3
vector = np.arange(10,66)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65])

In [64]:
#4
vector[::-1]

array([65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [65]:
#5
vector= np.arange(0,9).reshape(3,3)
vector

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])